import type { MainSkill, Skill, SkillsRelation } from "./types";

export const getSkillsGraph = async (): Promise<{
  mainSkill: MainSkill;
  nodes: Skill[];
  edges: SkillsRelation[];
}> => {
  return {
    mainSkill: {
      id: "1",
      title: "Машинное обучение",
      description: "Описание машинного обучения",
    },
    nodes: [
      // Уровень 1
      {
        id: "2",
        title: "Математика",
        description: "Описание математики",
        learnHours: 10,
        priority: 1,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "3",
        title: "Python",
        description: "Описание Python",
        learnHours: 20,
        priority: 2,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "4",
        title: "Обработка данных",
        description: "Описание обработки данных",
        learnHours: 15,
        priority: 2,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "5",
        title: "Машинное зрение",
        description: "Описание машинного зрения",
        learnHours: 18,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "6",
        title: "Обучение с подкреплением",
        description: "Описание RL",
        learnHours: 20,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },

      // Уровень 2
      {
        id: "7",
        title: "Линейная алгебра",
        description: "Описание линейной алгебры",
        learnHours: 12,
        priority: 1,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [
          {
            title: "Линейная алгебра: четыре разных подхода к одной задаче",
            link: "https://habr.com/ru/articles/953338/",
            rating: 76,
            tags: ["Математика", "Учебный процесс в IT"],
            description:
              "В этой статье разберем четыре задачи из студенческих олимпиад по математике. Условие везде такое: возвести матрицу в какую-то большую степень. Но вместе с этим мы увидим, что в зависимости от того под каким углом посмотреть на задачу актуальными оказываются самые разные разделы линейной алгебры. Поехали",
          },
        ],
        books: [
          {
            author: "А. И. Кострикин",
            title: "Введение в алгебру. Часть 2. Линейная алгебра",
            description:
              "один из самых популярных университетских учебников, где сложные темы изложены максимально доступно.",
            id: "123",
            link: "https://elar.urfu.ru/bitstream/10995/78551/1/978-5-7996-2776-8_2019.pdf",
          },
        ],
        courses: [
          {
            title: "Линейная алгебра",
            link: "https://stepik.org/course/83142/promo",
            learningTimeInfo: {
              maxHours: 11,
              minHours: 7,
              avgHours: 9,
              coursesAnalyzed: 1,
            },
            description:
              "Курс знакомит слушателей с основными разделами линейной алгебры: теория матриц, теория решения систем линейных алгебраических уравнений, линейные пространства и подпространства, линейные операторы, квадратичные формы, а также с элементами геометрии на плоскости и в пространстве.",
            id: "123",
          },
        ],
      },
      {
        id: "8",
        title: "Статистика",
        description: "Описание статистики",
        learnHours: 12,
        priority: 1,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "9",
        title: "NumPy",
        description: "Описание библиотеки NumPy",
        learnHours: 8,
        priority: 2,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "10",
        title: "Pandas",
        description: "Описание библиотеки Pandas",
        learnHours: 8,
        priority: 2,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "11",
        title: "Визуализация данных",
        description: "Описание визуализации",
        learnHours: 10,
        priority: 2,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "12",
        title: "OpenCV",
        description: "Описание OpenCV",
        learnHours: 15,
        priority: 2,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "13",
        title: "Среда Gym",
        description: "Описание Gym для RL",
        learnHours: 10,
        priority: 2,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },

      // Уровень 3
      {
        id: "14",
        title: "Регрессия",
        description: "Описание регрессии",
        learnHours: 15,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "15",
        title: "Классификация",
        description: "Описание классификации",
        learnHours: 15,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "16",
        title: "Кластеризация",
        description: "Описание кластеризации",
        learnHours: 12,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "17",
        title: "Глубокое обучение",
        description: "Описание глубокого обучения",
        learnHours: 20,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "18",
        title: "CNN",
        description: "Сверточные нейронные сети",
        learnHours: 18,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "19",
        title: "DQN",
        description: "Deep Q-Learning",
        learnHours: 18,
        priority: 3,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },

      // Уровень 4
      {
        id: "20",
        title: "Обнаружение объектов",
        description: "Описание детекции объектов",
        learnHours: 15,
        priority: 4,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "21",
        title: "Сегментация изображений",
        description: "Описание сегментации",
        learnHours: 15,
        priority: 4,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
      {
        id: "22",
        title: "Игра в CartPole",
        description: "Пример обучения RL на CartPole",
        learnHours: 12,
        priority: 4,
        isArchieved: false,
        isCompleted: false,
        isRequired: false,
        articles: [],
        books: [],
        courses: [],
      },
    ],
    edges: [
      // Уровень 1
      { fromId: "1", toId: "2" },
      { fromId: "1", toId: "3" },
      { fromId: "1", toId: "4" },
      { fromId: "1", toId: "5" },
      { fromId: "1", toId: "6" },

      // Уровень 2
      { fromId: "2", toId: "7" },
      { fromId: "2", toId: "8" },
      { fromId: "3", toId: "9" },
      { fromId: "3", toId: "10" },
      { fromId: "4", toId: "11" },
      { fromId: "5", toId: "12" },
      { fromId: "6", toId: "13" },

      // Уровень 3
      { fromId: "7", toId: "14" },
      { fromId: "8", toId: "15" },
      { fromId: "9", toId: "16" },
      { fromId: "10", toId: "17" },
      { fromId: "12", toId: "18" },
      { fromId: "13", toId: "19" },

      // Уровень 4
      { fromId: "18", toId: "20" },
      { fromId: "18", toId: "21" },
      { fromId: "19", toId: "22" },
    ],
  };
};
